apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: org-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: my
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      path: ''
      repoURL: 'https://kubernetes-charts.storage.googleapis.com'
      targetRevision: 5.0.2
      chart: wordpress