apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: org-3-custom
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: my
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ''
    repoURL: 'https://charts.helm.sh/stable'
    targetRevision: 9.0.3
    chart: wordpress
  syncPolicy:
    syncOptions:
      - CreateNamespace=true